### ISSUE TITLE
Support pseudo-type "callable"

### ISSUE THREAD

**Issue by brightbyte** [wmde/Assert#3]
When checking parameter types, "callable" should work.

**Comment by thiemowmde** [comment]
Agree. The PHP function is called `is_callable`, ~~is_callback~~ doesn't exist. [`callback` should be avoided as a type hint nowadays in favour of `callable`](http://php.net/manual/en/language.pseudo-types.php#language.types.callback).

**Comment by thiemowmde** [comment]
Supported since 7c368504a2e502082dbad5d3d0d7ff9ea76c9d17.
